import type { LocalSttModelInfo, LocalLlmModelInfo } from './tauri.types';

export const DEV_LOCAL_STT_MANIFESTS: Omit<LocalSttModelInfo, 'is_downloaded' | 'is_downloading' | 'partial_size'>[] = [
  {
    id: 'whisper-small',
    name: 'Whisper Small',
    description: 'Multilingual offline speech with Context vocabulary hints. Portable whisper.cpp CPU engine.',
    filename: 'ggml-small.bin',
    url: 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin',
    sha256: '1be3a9b2063867b937e64e2ec7483364a79917e157fa98c5d94b5c1fffea987b',
    size_mb: 465,
    is_directory: false,
    engine_type: 'whisper',
    speed_score: 2.0,
    accuracy_score: 3.5,
    privacy_label: 'Runs on this device',
    supported_languages: ['Multilingual'],
    supports_language_selection: true,
    supports_translation: false,
    is_recommended: false,
  },
  {
    id: 'whisper-large-v3-turbo',
    name: 'Whisper Large V3 Turbo',
    description: 'Larger multilingual offline speech with Context vocabulary hints. Portable whisper.cpp CPU engine.',
    filename: 'ggml-large-v3-turbo.bin',
    url: 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin',
    sha256: '1fc70f774d38eb169993ac391eea357ef47c88757ef72ee5943879b7e8e2bc69',
    size_mb: 1550,
    is_directory: false,
    engine_type: 'whisper',
    speed_score: 1.5,
    accuracy_score: 4.0,
    privacy_label: 'Runs on this device',
    supported_languages: ['Multilingual'],
    supports_language_selection: true,
    supports_translation: false,
    is_recommended: false,
  },
  {
    id: 'parakeet-v3',
    name: 'Parakeet V3',
    description: 'Fast and accurate. Supports 25 European languages.',
    filename: 'parakeet-v3-int8.tar.gz',
    url: 'https://blob.handy.computer/parakeet-v3-int8.tar.gz',
    sha256: '43d37191602727524a7d8c6da0eef11c4ba24320f5b4730f1a2497befc2efa77',
    size_mb: 456,
    is_directory: true,
    engine_type: 'parakeet',
    speed_score: 4.25,
    accuracy_score: 4.0,
    privacy_label: 'Runs on this device',
    supported_languages: [
      'Bulgarian', 'Croatian', 'Czech', 'Danish', 'Dutch', 'English', 'Estonian', 'Finnish',
      'French', 'German', 'Greek', 'Hungarian', 'Italian', 'Latvian', 'Lithuanian', 'Maltese',
      'Polish', 'Portuguese', 'Romanian', 'Slovak', 'Slovenian', 'Spanish', 'Swedish',
      'Russian', 'Ukrainian',
    ],
    supports_language_selection: false,
    supports_translation: false,
    is_recommended: true,
  },
  {
    id: 'parakeet-v2',
    name: 'Parakeet V2',
    description: 'English-only alternative to Parakeet V3 with slightly higher English accuracy.',
    filename: 'parakeet-v2-int8.tar.gz',
    url: 'https://blob.handy.computer/parakeet-v2-int8.tar.gz',
    sha256: 'ac9b9429984dd565b25097337a887bb7f0f8ac393573661c651f0e7d31563991',
    size_mb: 451,
    is_directory: true,
    engine_type: 'parakeet',
    speed_score: 4.25,
    accuracy_score: 4.25,
    privacy_label: 'Runs on this device',
    supported_languages: ['English'],
    supports_language_selection: false,
    supports_translation: false,
    is_recommended: false,
  },
  {
    id: 'moonshine-base',
    name: 'Moonshine Base',
    description: 'Smaller English model for weaker machines and faster local tests.',
    filename: 'moonshine-base.tar.gz',
    url: 'https://blob.handy.computer/moonshine-base.tar.gz',
    sha256: '04bf6ab012cfceebd4ac7cf88c1b31d027bbdd3cd704649b692e2e935236b7e8',
    size_mb: 187,
    is_directory: true,
    engine_type: 'moonshine',
    speed_score: 4.8,
    accuracy_score: 3.3,
    privacy_label: 'Runs on this device',
    supported_languages: ['English'],
    supports_language_selection: false,
    supports_translation: false,
    is_recommended: false,
  },
  {
    id: 'moonshine-tiny',
    name: 'Moonshine Tiny',
    description: 'Smallest and fastest English model. Best for low-power machines.',
    filename: 'moonshine-tiny-streaming-en.tar.gz',
    url: 'https://blob.handy.computer/moonshine-tiny-streaming-en.tar.gz',
    sha256: '465addcfca9e86117415677dfdc98b21edc53537210333a3ecdb58509a80abaf',
    size_mb: 31,
    is_directory: true,
    engine_type: 'moonshine_streaming',
    speed_score: 4.75,
    accuracy_score: 2.75,
    privacy_label: 'Runs on this device',
    supported_languages: ['English'],
    supports_language_selection: false,
    supports_translation: false,
    is_recommended: false,
  },
  {
    id: 'moonshine-small',
    name: 'Moonshine Small',
    description: 'Fast English model with a good balance of speed and accuracy.',
    filename: 'moonshine-small-streaming-en.tar.gz',
    url: 'https://blob.handy.computer/moonshine-small-streaming-en.tar.gz',
    sha256: 'dbb3e1c1832bd88a4ac712f7449a136cc2c9a18c5fe33a12ed1b7cb1cfe9cdd5',
    size_mb: 99,
    is_directory: true,
    engine_type: 'moonshine_streaming',
    speed_score: 4.5,
    accuracy_score: 3.25,
    privacy_label: 'Runs on this device',
    supported_languages: ['English'],
    supports_language_selection: false,
    supports_translation: false,
    is_recommended: false,
  },
  {
    id: 'moonshine-medium',
    name: 'Moonshine Medium',
    description: 'Higher quality English transcription, still fast.',
    filename: 'moonshine-medium-streaming-en.tar.gz',
    url: 'https://blob.handy.computer/moonshine-medium-streaming-en.tar.gz',
    sha256: '07a66f3bff1c77e75a2f637e5a263928a08baae3c29c4c053fc968a9a9373d13',
    size_mb: 192,
    is_directory: true,
    engine_type: 'moonshine_streaming',
    speed_score: 4.0,
    accuracy_score: 3.75,
    privacy_label: 'Runs on this device',
    supported_languages: ['English'],
    supports_language_selection: false,
    supports_translation: false,
    is_recommended: false,
  },
  {
    id: 'sense-voice',
    name: 'SenseVoice',
    description: 'Very fast multilingual model: Chinese, English, Japanese, Korean, Cantonese.',
    filename: 'sense-voice-int8.tar.gz',
    url: 'https://blob.handy.computer/sense-voice-int8.tar.gz',
    sha256: '171d611fe5d353a50bbb741b6f3ef42559b1565685684e9aa888ef563ba3e8a4',
    size_mb: 152,
    is_directory: true,
    engine_type: 'sense_voice',
    speed_score: 4.75,
    accuracy_score: 3.25,
    privacy_label: 'Runs on this device',
    supported_languages: ['Chinese', 'English', 'Japanese', 'Korean', 'Cantonese'],
    supports_language_selection: true,
    supports_translation: false,
    is_recommended: false,
  },
  {
    id: 'gigaam-v3',
    name: 'GigaAM v3',
    description: 'Dedicated Russian speech recognition. Fast and accurate.',
    filename: 'giga-am-v3-int8.tar.gz',
    url: 'https://blob.handy.computer/giga-am-v3-int8.tar.gz',
    sha256: 'd872462268430db140b69b72e0fc4b787b194c1dbe51b58de39444d55b6da45b',
    size_mb: 151,
    is_directory: true,
    engine_type: 'giga_am',
    speed_score: 3.75,
    accuracy_score: 4.25,
    privacy_label: 'Runs on this device',
    supported_languages: ['Russian'],
    supports_language_selection: false,
    supports_translation: false,
    is_recommended: false,
  },
  {
    id: 'canary-180m-flash',
    name: 'Canary 180M Flash',
    description: 'Small, fast multilingual model: English, German, Spanish, French. Supports translation.',
    filename: 'canary-180m-flash.tar.gz',
    url: 'https://blob.handy.computer/canary-180m-flash.tar.gz',
    sha256: '6d9cfca6118b296e196eaedc1c8fa9788305a7b0f1feafdb6dc91932ab6e53f7',
    size_mb: 146,
    is_directory: true,
    engine_type: 'canary',
    speed_score: 4.25,
    accuracy_score: 3.75,
    privacy_label: 'Runs on this device',
    supported_languages: ['English', 'German', 'Spanish', 'French'],
    supports_language_selection: true,
    supports_translation: true,
    is_recommended: false,
  },
  {
    id: 'canary-1b-v2',
    name: 'Canary 1B v2',
    description: 'Larger, more accurate multilingual model. 25 European languages. Supports translation.',
    filename: 'canary-1b-v2.tar.gz',
    url: 'https://blob.handy.computer/canary-1b-v2.tar.gz',
    sha256: '02305b2a25f9cf3e7deaffa7f94df00efa44f442cd55c101c2cb9c000f904666',
    size_mb: 691,
    is_directory: true,
    engine_type: 'canary',
    speed_score: 3.5,
    accuracy_score: 4.25,
    privacy_label: 'Runs on this device',
    supported_languages: [
      'Bulgarian', 'Croatian', 'Czech', 'Danish', 'Dutch', 'English', 'Estonian', 'Finnish',
      'French', 'German', 'Greek', 'Hungarian', 'Italian', 'Latvian', 'Lithuanian', 'Maltese',
      'Polish', 'Portuguese', 'Romanian', 'Slovak', 'Slovenian', 'Spanish', 'Swedish',
      'Russian', 'Ukrainian',
    ],
    supports_language_selection: true,
    supports_translation: true,
    is_recommended: false,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Largest and most accurate multilingual model. Covers European and East Asian languages, but slower.',
    filename: 'cohere-int8.tar.gz',
    url: 'https://blob.handy.computer/cohere-int8.tar.gz',
    sha256: 'ea2257d52434f3644574f187dcdcf666e302cd11b92866116ab8e14cd9c887f0',
    size_mb: 1708,
    is_directory: true,
    engine_type: 'cohere',
    speed_score: 3.0,
    accuracy_score: 4.5,
    privacy_label: 'Runs on this device',
    supported_languages: [
      'English', 'French', 'German', 'Italian', 'Spanish', 'Portuguese', 'Greek', 'Dutch',
      'Polish', 'Chinese', 'Japanese', 'Korean', 'Vietnamese', 'Arabic',
    ],
    supports_language_selection: true,
    supports_translation: false,
    is_recommended: false,
  },
];

export const DEV_LOCAL_LLM_MANIFESTS: Omit<LocalLlmModelInfo, 'is_downloaded' | 'is_downloading' | 'partial_size'>[] = [
  {
    id: 'gemma-4-e2b',
    name: 'Gemma 4 E2B',
    description: 'Best small default for local cleanup. Strong punctuation and instruction following.',
    repo_id: 'google/gemma-4-E2B-it-qat-q4_0-gguf',
    size_mb: 1640,
    quantization: 'Q4_0',
    privacy_label: 'Runs on this device',
    is_recommended: true,
    prompt_family: 'gemma4',
  },
  {
    id: 'qwen2.5-3b-instruct',
    name: 'Qwen 2.5 3B Instruct',
    description: 'Balanced local cleanup model with strong formatting control and good latency.',
    repo_id: 'Qwen/Qwen2.5-3B-Instruct-GGUF',
    size_mb: 1960,
    quantization: 'Q4_K_M',
    privacy_label: 'Runs on this device',
    is_recommended: true,
    prompt_family: 'qwen25',
  },
  {
    id: 'phi-3-mini-4k-instruct',
    name: 'Phi-3 Mini 4K Instruct',
    description: 'Compact Microsoft model with good cleanup reliability and a short context window.',
    repo_id: 'microsoft/Phi-3-mini-4k-instruct-gguf',
    size_mb: 2280,
    quantization: 'Q4',
    privacy_label: 'Runs on this device',
    is_recommended: true,
    prompt_family: 'phi3',
  },
  {
    id: 'qwen2.5-1.5b-instruct',
    name: 'Qwen 2.5 1.5B Instruct',
    description: 'Smaller Qwen option when you want decent cleanup on lighter hardware.',
    repo_id: 'Qwen/Qwen2.5-1.5B-Instruct-GGUF',
    size_mb: 1080,
    quantization: 'Q4_K_M',
    privacy_label: 'Runs on this device',
    is_recommended: true,
    prompt_family: 'qwen25',
  },
  {
    id: 'gemma-4-e4b',
    name: 'Gemma 4 E4B',
    description: 'Larger Gemma option with stronger cleanup quality when RAM allows it.',
    repo_id: 'google/gemma-4-E4B-it-qat-q4_0-gguf',
    size_mb: 3260,
    quantization: 'Q4_0',
    privacy_label: 'Runs on this device',
    is_recommended: true,
    prompt_family: 'gemma4',
  },
  {
    id: 'qwen2.5-0.5b-instruct',
    name: 'Qwen 2.5 0.5B Instruct',
    description: 'Tiny fallback for weak machines. Faster, but needs stricter cleanup prompting.',
    repo_id: 'Qwen/Qwen2.5-0.5B-Instruct-GGUF',
    size_mb: 430,
    quantization: 'Q4_K_M',
    privacy_label: 'Runs on this device',
    is_recommended: false,
    prompt_family: 'qwen25',
  },
  {
    id: 'qwen2.5-7b-instruct',
    name: 'Qwen 2.5 7B Instruct',
    description: 'Largest Qwen pick in the curated catalog. Good quality, much heavier download.',
    repo_id: 'Qwen/Qwen2.5-7B-Instruct-GGUF',
    size_mb: 4680,
    quantization: 'Q4_K_M',
    privacy_label: 'Runs on this device',
    is_recommended: false,
    prompt_family: 'qwen25',
  },
  {
    id: 'smollm2-360m-instruct',
    name: 'SmolLM2 360M Instruct',
    description: 'Extreme low-end option. Official repo only ships Q8, so it stays an advanced pick.',
    repo_id: 'HuggingFaceTB/SmolLM2-360M-Instruct-GGUF',
    size_mb: 390,
    quantization: 'Q8_0',
    privacy_label: 'Runs on this device',
    is_recommended: false,
    prompt_family: 'smollm2',
  },
  {
    id: 'smollm2-1.7b-instruct',
    name: 'SmolLM2 1.7B Instruct',
    description: 'Sharper than the 360M model while still staying relatively light.',
    repo_id: 'HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF',
    size_mb: 1030,
    quantization: 'Q4_K_M',
    privacy_label: 'Runs on this device',
    is_recommended: false,
    prompt_family: 'smollm2',
  },
  {
    id: 'granite-3.3-2b-instruct',
    name: 'Granite 3.3 2B Instruct',
    description: 'Compact Granite model with solid cleanup discipline and predictable formatting.',
    repo_id: 'ibm-granite/granite-3.3-2b-instruct-GGUF',
    size_mb: 1420,
    quantization: 'Q4_K_M',
    privacy_label: 'Runs on this device',
    is_recommended: false,
    prompt_family: 'granite33',
  },
  {
    id: 'granite-3.3-8b-instruct',
    name: 'Granite 3.3 8B Instruct',
    description: 'Biggest curated local cleanup model. Useful when quality matters more than load time.',
    repo_id: 'ibm-granite/granite-3.3-8b-instruct-GGUF',
    size_mb: 4910,
    quantization: 'Q4_K_M',
    privacy_label: 'Runs on this device',
    is_recommended: false,
    prompt_family: 'granite33',
  },
];
