use super::*;

pub(super) struct PipelineCompletionContext<'a> {
    pub(super) raw: &'a str,
    pub(super) final_text_before_dict: &'a str,
    pub(super) clipboard_plan: Option<&'a super::clipboard_phrase::ClipboardPhrasePlan>,
    pub(super) clipboard_warning: Option<&'static str>,
    pub(super) dict_entries: &'a [db::DictionaryEntry],
    pub(super) duration_ms: u64,
    pub(super) api_used: &'a str,
    pub(super) target_hwnd: usize,
    pub(super) cfg: &'a store::PipelineConfig,
    pub(super) profile: &'a str,
    pub(super) process_name: String,
    pub(super) cleanup_cache_key: String,
    pub(super) captured_at: std::time::Instant,
    pub(super) event_only: bool,
    pub(super) caps_lock_on: bool,
    pub(super) context: Option<&'a db::Context>,
}

fn dictionary_protects_initial_case(text: &str, entries: &[db::DictionaryEntry]) -> bool {
    let Some(start) = text
        .char_indices()
        .find_map(|(idx, ch)| ch.is_alphanumeric().then_some(idx))
    else {
        return false;
    };
    let leading = text.trim_start();
    let alphanumeric_leading = &text[start..];
    entries.iter().any(|entry| {
        !entry.term.is_empty()
            && entry.term.chars().any(char::is_uppercase)
            && [leading, alphanumeric_leading]
                .into_iter()
                .any(|candidate| {
                    candidate.strip_prefix(&entry.term).is_some_and(|rest| {
                        rest.chars()
                            .next()
                            .is_none_or(|ch| !ch.is_alphanumeric() && !matches!(ch, '\'' | '’'))
                    })
                })
    })
}

pub(super) async fn finalize_pipeline_completion(
    app: &AppHandle,
    state: &SharedState,
    ctx: PipelineCompletionContext<'_>,
) -> anyhow::Result<db::RecentEntry> {
    let dict_stage = std::time::Instant::now();
    let (mut final_text_substituted, mut applied_dict_ids) =
        dictionary::apply_substitutions_from(ctx.final_text_before_dict, ctx.dict_entries);
    let mut dict_changed = !applied_dict_ids.is_empty();
    let apply_caps_lock_upper = ctx.cfg.caps_lock_uppercase_enabled && ctx.caps_lock_on;
    // Logged unconditionally (not just when applied) so a report of
    // unexpected ALL CAPS output is actually diagnosable: did the setting
    // fire on a stale/incorrect caps_lock_on read, or is the uppercasing
    // coming from somewhere else entirely (e.g. the cleanup model itself)?
    log::debug!(
        "pipeline: caps lock uppercase setting_enabled={} detected_caps_lock_on={} applied={}",
        ctx.cfg.caps_lock_uppercase_enabled,
        ctx.caps_lock_on,
        apply_caps_lock_upper
    );
    if apply_caps_lock_upper {
        final_text_substituted = final_text_substituted.to_uppercase();
    }
    // The marker is intentionally the only clipboard-related content that can
    // pass through text transforms. Restore exact bytes only after them.
    let (final_text_substituted, delivered_text, private_text, clipboard_warning) =
        if let Some(plan) = ctx.clipboard_plan {
            let marker_survived = plan
                .markers
                .iter()
                .all(|marker| final_text_substituted.matches(marker).count() == 1);
            let marker_text = if marker_survived {
                final_text_substituted
            } else {
                log::warn!("pipeline: cleanup did not preserve clipboard marker");
                // Re-run deterministic dictionary work against the protected
                // pre-clean representation. This keeps safe dictated-range
                // corrections even when the cleanup model damages a marker.
                let (mut fallback, fallback_dict_ids) =
                    dictionary::apply_substitutions_from(&plan.pre_cleanup, ctx.dict_entries);
                applied_dict_ids = fallback_dict_ids;
                dict_changed = !applied_dict_ids.is_empty();
                if apply_caps_lock_upper {
                    fallback = fallback.to_uppercase();
                }
                fallback
            };
            let delivered =
                super::clipboard_phrase::restore(&marker_text, plan).unwrap_or_else(|| {
                    log::error!("pipeline: generated clipboard markers were not restorable");
                    // `pre_cleanup` is generated by Verenu and is therefore the
                    // last safe representation even if a future change makes the
                    // normal marker validation stricter.
                    plan.markers
                        .iter()
                        .fold(plan.pre_cleanup.clone(), |text, marker| {
                            text.replace(marker, &plan.clipboard_text)
                        })
                });
            let private = super::clipboard_phrase::private_text(&marker_text, plan);
            (
                marker_text,
                delivered,
                private,
                if !marker_survived {
                    Some("Clipboard inserted without cleanup")
                } else {
                    ctx.clipboard_warning
                },
            )
        } else {
            let text = final_text_substituted;
            (text.clone(), text.clone(), text, ctx.clipboard_warning)
        };
    log::debug!(
        "pipeline: dictionary apply changed={} before_chars={} after_chars={} stage_ms={}",
        dict_changed,
        ctx.final_text_before_dict.chars().count(),
        final_text_substituted.chars().count(),
        dict_stage.elapsed().as_millis()
    );
    if dict_changed && crate::system::logger::is_verbose() {
        log::debug!(
            "pipeline: dictionary before_full=\"{}\"",
            ctx.final_text_before_dict
        );
        log::debug!(
            "pipeline: dictionary after_full=\"{}\"",
            final_text_substituted
        );
    }

    let db_handle = app.state::<DbHandle>();
    let words = ctx.raw.split_whitespace().count() as i64;
    let db_for_insert = db_handle.inner().clone();
    let raw_for_insert = ctx.raw.to_string();
    // History's per-entry app metadata is the lowercase executable name. The
    // "unknown" fallback from window_context carries no signal (failed read /
    // lost foreground), so it is stored as NULL and simply has no app.
    let app_name_for_insert = (!ctx.process_name.is_empty() && ctx.process_name != "unknown")
        .then(|| ctx.process_name.clone());
    // `final_text_substituted` already has caps-lock uppercasing AND
    // dictionary substitution applied (see above) — it's the same text that
    // gets injected below. History must save exactly that, not
    // `final_text_before_dict`: saving the pre-dictionary text here meant a
    // dictionary correction could be applied correctly to what actually got
    // pasted while History silently kept showing the uncorrected version
    // forever, which is also what misled diagnosis of this exact bug.
    let clean_for_insert = private_text.clone();
    let api_used_for_insert = ctx.api_used.to_string();
    let duration_for_insert = ctx.duration_ms as i64;
    let dictionary_fixes_applied = applied_dict_ids.len() as i64;
    // Attributes the dictation to whichever context resolved for it, so the
    // context page can show real totals. `None` when resolution failed.
    let context_for_insert = ctx.context.map(|context| context.id);
    let entry = match tokio::task::spawn_blocking(move || -> anyhow::Result<db::RecentEntry> {
        let entry = db::insert_transcription_returning(
            &db_for_insert,
            &raw_for_insert,
            &clean_for_insert,
            words,
            duration_for_insert,
            &api_used_for_insert,
            app_name_for_insert.as_deref(),
            context_for_insert,
        )?;
        if dictionary_fixes_applied > 0 {
            // Lifetime counter for the Insights "fixes made by Verenu" card;
            // same never-recomputed pattern as total_words. Best-effort —
            // a failed counter must not fail the dictation itself.
            if let Err(e) =
                db::increment_lifetime_dictionary_fixes(&db_for_insert, dictionary_fixes_applied)
            {
                log::warn!("pipeline: failed to record dictionary fixes: {e}");
            }
        }
        Ok(entry)
    })
    .await
    {
        Ok(Ok(entry)) => {
            super::failover::discard_durable();
            if let Ok(mut st) = lock_state(state) {
                st.failover_session_id = None;
                st.failover_reuse_id = false;
                st.failover_started_at_unix = 0;
            }
            entry
        }
        Ok(Err(e)) => {
            show_error_pill(
                app,
                &format!("Failed to save transcription: {}", trim_err(&e.to_string())),
            )
            .await;
            return Err(e);
        }
        Err(e) => {
            show_error_pill(app, "Failed to save transcription: background task crashed").await;
            return Err(anyhow::anyhow!("insert_transcription task panicked: {e}"));
        }
    };

    // Per-call API usage records for the Insights cost card. Best-effort:
    // a failed audit row must never fail the dictation that already
    // inserted fine above. Only counts and model ids are ever logged.
    let calls = db::build_api_calls(
        entry.id,
        &entry.created_at,
        ctx.api_used,
        ctx.duration_ms as i64,
        ctx.raw,
        &private_text,
    );
    if !calls.is_empty() {
        let db_for_calls = db_handle.inner().clone();
        match tokio::task::spawn_blocking(move || db::insert_api_calls(&db_for_calls, &calls)).await
        {
            Ok(Ok(())) => {}
            Ok(Err(e)) => {
                log::warn!(
                    "pipeline: failed to record api usage rows: {}",
                    trim_err(&e.to_string())
                )
            }
            Err(e) => log::warn!("pipeline: api usage recording task panicked: {e}"),
        }
    }

    if let Ok(mut st) = lock_state(state) {
        if st.retry_capture.as_ref().map(|v| v.captured_at) == Some(ctx.captured_at) {
            st.retry_capture = None;
        }
    }

    let inject_stage = std::time::Instant::now();
    let protected_initial_case =
        dictionary_protects_initial_case(&delivered_text, ctx.dict_entries);

    // If Verenu itself has foreground focus, a Ctrl+V / Cmd+V paste would
    // land in our own WebView with no active text field and silently disappear.
    // Detect this by PID and fall back to clipboard-only so the user can paste manually.
    let self_inject = foreground_is_own_process() || hwnd_is_own_process(ctx.target_hwnd);
    log::debug!(
        "pipeline: injection decision target_hwnd={} event_only={} self_inject={}",
        ctx.target_hwnd,
        ctx.event_only,
        self_inject
    );

    let clipboard_is_leading = ctx.clipboard_plan.is_some_and(|plan| {
        plan.markers
            .first()
            .is_some_and(|marker| final_text_substituted.trim_start().starts_with(marker))
    });
    let injected = if ctx.event_only {
        injection::InjectionOutcome {
            text: delivered_text.clone(),
            context_state: "event_only",
            case_decision: "setup_try_event",
            probe_source: "unavailable",
            selection_state: "unknown",
        }
    } else if self_inject {
        log::info!("pipeline: self-inject detected — clipboard fallback");
        if let Err(e) = injection::copy_to_clipboard(&delivered_text).await {
            log::warn!("pipeline: clipboard fallback write failed: {e}");
        }
        // This is an informational success, not an error: use the pill's
        // "copied" state instead of verenu:error, which renders as a red
        // toast in the main window.
        show_copied_pill(app, "Text copied — press Ctrl+V to paste");
        injection::InjectionOutcome {
            text: delivered_text.clone(),
            context_state: "self_inject",
            case_decision: "clipboard_fallback",
            probe_source: "unavailable",
            selection_state: "unknown",
        }
    } else {
        match injection::inject_text(
            &delivered_text,
            ctx.target_hwnd,
            // Caps lock must be the final word on casing: contextual capitalization
            // (e.g. lowercasing a continuation's first letter) would otherwise run
            // on top of the all-caps text and undo part of it.
            ctx.cfg.contextual_formatting_enabled
                && !apply_caps_lock_upper
                && !clipboard_is_leading,
            ctx.cfg.contextual_formatting_enabled,
            ctx.profile,
            &ctx.cfg.transcription_language,
            protected_initial_case,
        )
        .await
        {
            Ok(outcome) => outcome,
            Err(e) => {
                log::error!("inject: {e}");
                if let Ok(mut st) = lock_state(state) {
                    st.paste_failure = Some(PasteFailure {
                        text: delivered_text.clone(),
                        captured_at: std::time::Instant::now(),
                    });
                }
                show_paste_failed_pill(app);
                injection::InjectionOutcome {
                    text: delivered_text.clone(),
                    context_state: "unknown",
                    case_decision: "inject_failed",
                    probe_source: "unavailable",
                    selection_state: "unknown",
                }
            }
        }
    };
    let injected_text = injected.text;
    log::debug!(
        "pipeline: delivery done contextual_formatting={} context_state={} case_decision={} probe_source={} selection_state={} output_chars={} stage_ms={}",
        ctx.cfg.contextual_formatting_enabled,
        injected.context_state,
        injected.case_decision,
        injected.probe_source,
        injected.selection_state,
        injected_text.chars().count(),
        inject_stage.elapsed().as_millis()
    );
    app.emit("verenu:transcribed", &injected_text).ok();

    if ctx.event_only {
        hide_pill(app);
        return Ok(entry);
    }

    // Don't stomp the "Paste failed" pill (with its Copy button) that
    // show_paste_failed_pill just showed a few lines up — hide_pill would
    // instantly revert it to idle before the button even has a chance to
    // fade in, let alone be clicked.
    if injected.case_decision == "inject_failed" || injected.case_decision == "clipboard_fallback" {
        log::debug!(
            "pipeline: preserving terminal pill state case_decision={}",
            injected.case_decision
        );
    } else if let Some(message) = clipboard_warning {
        // Replace the processing pill directly so a passive warning does not
        // flash through idle on its way to the final state.
        super::show_clipboard_warning_pill(app, message);
    } else {
        hide_pill(app);
    }

    // Clipboard-expanded output is intentionally not monitored: its exact
    // text must stay out of correction/focused-text probes, and the private
    // placeholder cannot match the text that was delivered to the editor.
    if ctx.clipboard_plan.is_none() {
        if !ctx.cleanup_cache_key.is_empty() {
            auto_learn::start_cache_rejection_monitor(
                private_text.clone(),
                ctx.cleanup_cache_key,
                ctx.target_hwnd,
                db_handle.inner().clone(),
                app.clone(),
            );
        }
        if ctx.cfg.auto_learn_enabled {
            if !applied_dict_ids.is_empty() {
                auto_learn::start_rejection_monitor(
                    private_text.clone(),
                    applied_dict_ids,
                    ctx.target_hwnd,
                    db_handle.inner().clone(),
                    app.clone(),
                );
            }
            auto_learn::start_monitor(
                private_text,
                ctx.process_name,
                db_handle.inner().clone(),
                app.clone(),
            );
        }
    }

    Ok(entry)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(term: &str) -> db::DictionaryEntry {
        db::DictionaryEntry {
            id: 1,
            term: term.to_string(),
            mistake: None,
            auto_learned: false,
            correction_count: 0,
            confidence_tier: "confirmed".to_string(),
            last_seen_at: None,
            created_at: String::new(),
        }
    }

    #[test]
    fn dictionary_case_protection_only_matches_an_exact_leading_term() {
        let entries = [entry("Verenu")];
        assert!(dictionary_protects_initial_case(
            "\"Verenu works\"",
            &entries
        ));
        assert!(dictionary_protects_initial_case(
            ".NET is a useful platform",
            &[entry(".NET")]
        ));
        assert!(!dictionary_protects_initial_case("Very useful", &entries));
        assert!(!dictionary_protects_initial_case("Use Verenu", &entries));
    }
}
