// Generated by scripts/generate-icons.ps1 from icons/verenu-mark.svg.
// Do not edit the bar coordinates here; change the canonical SVG and regenerate.

#[allow(dead_code)]
#[derive(Clone, Copy)]
pub(crate) struct CanonicalBar {
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
    pub radius: u32,
}

#[allow(dead_code)]
pub(crate) const CANONICAL_MARK_WIDTH: u32 = 254;
pub(crate) const CANONICAL_MARK_HEIGHT: u32 = 208;
pub(crate) const CANONICAL_BARS: [CanonicalBar; 5] = [
    CanonicalBar { x: 0, y: 138, width: 38, height: 70, radius: 19 },
    CanonicalBar { x: 54, y: 68, width: 38, height: 140, radius: 19 },
    CanonicalBar { x: 108, y: 0, width: 38, height: 208, radius: 19 },
    CanonicalBar { x: 162, y: 88, width: 38, height: 120, radius: 19 },
    CanonicalBar { x: 216, y: 146, width: 38, height: 62, radius: 19 },
];
